export const API_URL = {
  LOGIN: 'http://localhost:5000/auth/login',
  REGISTER: 'http://localhost:5000/auth/register',
  ADD_AVATAR: 'http://localhost:5000/user/photo',
  REGISTER_ADDITIONAL: 'http://localhost:5000/auth/additional',
  DELETE: 'http://localhost:5000/menu/delete',
  ADD: 'http://localhost:5000/menu/add',
  ADD_PRODUCT: 'http://localhost:5000/product/add',
  GET_ALL_MENUS: 'http://localhost:5000/menu/list',
  GET_ALL_PRODUCTS: 'http://localhost:5000/product/list',
  GET_ALL_INGREDIENTS: 'http://localhost:5000/ingredient/list/',
  GET_ALL_ALLERGENS: 'http://localhost:5000/allergen/list',
  GET_PRODUCT: 'http://localhost:5000/product/',
  GET_PRODUCT_BY_ID: 'http://localhost:5000/product/get/',
  GET_MENU: 'http://localhost:5000/menu/get/',
  SEARCH_ALL_PRODUCTS: 'http://localhost:5000/product/list/param',
};
