export const API = {
  AUTH: '/auth',
  USERS: '/users',
  USER: '/user',
  LOG_IN: '/login',
  SIGN_UP: '/register',
  ADDITIONAL: '/additional',
  RETRIEVE_USER_INFO: '/retrieve-user',
  MENU: '/menu',
  PRODUCT: '/product',
  ORDER: '/order',
  INGREDIENT: '/ingredient',
  ALLERGEN: '/allergen',
  ADDRESS: '/address',
  COMMENT: '/comment',
  ADD: '/add',
  DELETE: '/delete',
  GET: '/get',
  LIST: '/list',
  UPDATE: '/update',
  ID_PARAM: '/:id',
};
